### ISSUE TITLE
I got this error even after setting Resnet18 and resnet 50 paths.

### ISSUE THREAD

**Issue by Affan-Abbas8** [ArminMasoumian/GCNDepth#11]
![capa](https://user-images.githubusercontent.com/119195312/204903397-daebcb8a-4e9b-4572-93f0-00a550f40494.PNG)

Also, I need to ask what should I place here.
In the extractor pretrained path?
![Capture](https://user-images.githubusercontent.com/119195312/204903583-cea78d2b-7897-45de-8086-e48dff10b625.PNG)
I placed the pre-trained weights file path here but it didn't work.
Thank you in anticipation.

**Comment by ArminMasoumian** [comment]
You can find the pre-trained weights here:
https://drive.google.com/file/d/1BImXNB9PEgv3mZczB3uBW3EDi4dpOcXF/view

It seems the problem is coming from the torch, did you install the requirements with the same version? you can find the versions in the requirements.txt

Also, you need to set up your GPU and run our code on GPU, it cannot be run on the CPU because of the complexity of the code. Please double-check that your Cuda is working as well.

**Comment by Affan-Abbas8** [comment]
thanks for your response.
Yes, now I again installed all the requirements and the issue changed now.
Here is the screen shot.
Plz take a look and let me know about it.

![capta](https://user-images.githubusercontent.com/119195312/205004397-f46cd657-bf71-4403-ac1f-3e938899ebf7.PNG)

**Comment by Affan-Abbas8** [comment]
![Capture](https://user-images.githubusercontent.com/119195312/205021392-17e5d6f2-4cf7-4309-bc8e-09547a2390da.PNG)
Should I change something here as well?

**Comment by Affan-Abbas8** [comment]
and should I have to change the path in config_kitti_autoencder too?
![Capture](https://user-images.githubusercontent.com/119195312/205026595-ed7570cc-002b-4c41-9639-b917c701764d.PNG)

**Comment by Affan-Abbas8** [comment]
thanks for your response.
can you plz share the link to kitti_data and gt_depth.npz?
